/* SPDX-License-Identifier: ((GPL-2.0 WITH Linux-syscall-note) OR BSD-3-Clause) */
/* Do not edit directly, auto-generated from: */
/*	Documentation/netlink/specs/dev-energy-model.yaml */
/* YNL-GEN uapi header */
/* To regenerate run: tools/net/ynl/ynl-regen.sh */

#ifndef _UAPI_LINUX_DEV_ENERGY_MODEL_H
#define _UAPI_LINUX_DEV_ENERGY_MODEL_H

#define DEV_ENERGY_MODEL_FAMILY_NAME	"dev-energy-model"
#define DEV_ENERGY_MODEL_FAMILY_VERSION	1

/**
 * enum dev_energy_model_perf_state_flags
 * @DEV_ENERGY_MODEL_PERF_STATE_FLAGS_PERF_STATE_INEFFICIENT: The performance
 *   state is inefficient. There is in this perf-domain, another performance
 *   state with a higher frequency but a lower or equal power cost.
 */
enum dev_energy_model_perf_state_flags {
	DEV_ENERGY_MODEL_PERF_STATE_FLAGS_PERF_STATE_INEFFICIENT = 1,
};

/**
 * enum dev_energy_model_perf_domain_flags
 * @DEV_ENERGY_MODEL_PERF_DOMAIN_FLAGS_PERF_DOMAIN_MICROWATTS: The power values
 *   are in micro-Watts or some other scale.
 * @DEV_ENERGY_MODEL_PERF_DOMAIN_FLAGS_PERF_DOMAIN_SKIP_INEFFICIENCIES: Skip
 *   inefficient states when estimating energy consumption.
 * @DEV_ENERGY_MODEL_PERF_DOMAIN_FLAGS_PERF_DOMAIN_ARTIFICIAL: The power values
 *   are artificial and might be created by platform missing real power
 *   information.
 */
enum dev_energy_model_perf_domain_flags {
	DEV_ENERGY_MODEL_PERF_DOMAIN_FLAGS_PERF_DOMAIN_MICROWATTS = 1,
	DEV_ENERGY_MODEL_PERF_DOMAIN_FLAGS_PERF_DOMAIN_SKIP_INEFFICIENCIES = 2,
	DEV_ENERGY_MODEL_PERF_DOMAIN_FLAGS_PERF_DOMAIN_ARTIFICIAL = 4,
};

enum {
	DEV_ENERGY_MODEL_A_PERF_DOMAINS_PERF_DOMAIN_ID = 1,
	DEV_ENERGY_MODEL_A_PERF_DOMAINS_PERF_DOMAIN,

	__DEV_ENERGY_MODEL_A_PERF_DOMAINS_MAX,
	DEV_ENERGY_MODEL_A_PERF_DOMAINS_MAX = (__DEV_ENERGY_MODEL_A_PERF_DOMAINS_MAX - 1)
};

enum {
	DEV_ENERGY_MODEL_A_PERF_DOMAIN_PAD = 1,
	DEV_ENERGY_MODEL_A_PERF_DOMAIN_PERF_DOMAIN_ID,
	DEV_ENERGY_MODEL_A_PERF_DOMAIN_FLAGS,
	DEV_ENERGY_MODEL_A_PERF_DOMAIN_CPUS,

	__DEV_ENERGY_MODEL_A_PERF_DOMAIN_MAX,
	DEV_ENERGY_MODEL_A_PERF_DOMAIN_MAX = (__DEV_ENERGY_MODEL_A_PERF_DOMAIN_MAX - 1)
};

enum {
	DEV_ENERGY_MODEL_A_PERF_TABLE_PERF_DOMAIN_ID = 1,
	DEV_ENERGY_MODEL_A_PERF_TABLE_PERF_STATE,

	__DEV_ENERGY_MODEL_A_PERF_TABLE_MAX,
	DEV_ENERGY_MODEL_A_PERF_TABLE_MAX = (__DEV_ENERGY_MODEL_A_PERF_TABLE_MAX - 1)
};

enum {
	DEV_ENERGY_MODEL_A_PERF_STATE_PAD = 1,
	DEV_ENERGY_MODEL_A_PERF_STATE_PERFORMANCE,
	DEV_ENERGY_MODEL_A_PERF_STATE_FREQUENCY,
	DEV_ENERGY_MODEL_A_PERF_STATE_POWER,
	DEV_ENERGY_MODEL_A_PERF_STATE_COST,
	DEV_ENERGY_MODEL_A_PERF_STATE_FLAGS,

	__DEV_ENERGY_MODEL_A_PERF_STATE_MAX,
	DEV_ENERGY_MODEL_A_PERF_STATE_MAX = (__DEV_ENERGY_MODEL_A_PERF_STATE_MAX - 1)
};

enum {
	DEV_ENERGY_MODEL_CMD_GET_PERF_DOMAINS = 1,
	DEV_ENERGY_MODEL_CMD_GET_PERF_TABLE,
	DEV_ENERGY_MODEL_CMD_PERF_DOMAIN_CREATED,
	DEV_ENERGY_MODEL_CMD_PERF_DOMAIN_UPDATED,
	DEV_ENERGY_MODEL_CMD_PERF_DOMAIN_DELETED,

	__DEV_ENERGY_MODEL_CMD_MAX,
	DEV_ENERGY_MODEL_CMD_MAX = (__DEV_ENERGY_MODEL_CMD_MAX - 1)
};

#define DEV_ENERGY_MODEL_MCGRP_EVENT	"event"

#endif /* _UAPI_LINUX_DEV_ENERGY_MODEL_H */
