/* SPDX-License-Identifier: ((GPL-2.0 WITH Linux-syscall-note) OR BSD-3-Clause) */
/* Do not edit directly, auto-generated from: */
/*	Documentation/netlink/specs/device-energy-model.yaml */
/* YNL-GEN uapi header */
/* To regenerate run: tools/net/ynl/ynl-regen.sh */

#ifndef _UAPI_LINUX_DEVICE_ENERGY_MODEL_H
#define _UAPI_LINUX_DEVICE_ENERGY_MODEL_H

#define DEVICE_ENERGY_MODEL_FAMILY_NAME		"device-energy-model"
#define DEVICE_ENERGY_MODEL_FAMILY_VERSION	1

/**
 * enum device_energy_model_perf_state_flags
 * @DEVICE_ENERGY_MODEL_PERF_STATE_FLAGS_PERF_STATE_INEFFICIENT: The
 *   performance state is inefficient. There is in this perf-domain, another
 *   performance state with a higher frequency but a lower or equal power cost.
 */
enum device_energy_model_perf_state_flags {
	DEVICE_ENERGY_MODEL_PERF_STATE_FLAGS_PERF_STATE_INEFFICIENT = 1,
};

/**
 * enum device_energy_model_perf_domain_flags
 * @DEVICE_ENERGY_MODEL_PERF_DOMAIN_FLAGS_PERF_DOMAIN_MICROWATTS: The power
 *   values are in micro-Watts or some other scale.
 * @DEVICE_ENERGY_MODEL_PERF_DOMAIN_FLAGS_PERF_DOMAIN_SKIP_INEFFICIENCIES: Skip
 *   inefficient states when estimating energy consumption.
 * @DEVICE_ENERGY_MODEL_PERF_DOMAIN_FLAGS_PERF_DOMAIN_ARTIFICIAL: The power
 *   values are artificial and might be created by platform missing real power
 *   information.
 */
enum device_energy_model_perf_domain_flags {
	DEVICE_ENERGY_MODEL_PERF_DOMAIN_FLAGS_PERF_DOMAIN_MICROWATTS = 1,
	DEVICE_ENERGY_MODEL_PERF_DOMAIN_FLAGS_PERF_DOMAIN_SKIP_INEFFICIENCIES = 2,
	DEVICE_ENERGY_MODEL_PERF_DOMAIN_FLAGS_PERF_DOMAIN_ARTIFICIAL = 4,
};

enum {
	DEVICE_ENERGY_MODEL_A_PERF_DOMAINS_PERF_DOMAIN_ID = 1,
	DEVICE_ENERGY_MODEL_A_PERF_DOMAINS_PERF_DOMAIN,

	__DEVICE_ENERGY_MODEL_A_PERF_DOMAINS_MAX,
	DEVICE_ENERGY_MODEL_A_PERF_DOMAINS_MAX = (__DEVICE_ENERGY_MODEL_A_PERF_DOMAINS_MAX - 1)
};

enum {
	DEVICE_ENERGY_MODEL_A_PERF_DOMAIN_PAD = 1,
	DEVICE_ENERGY_MODEL_A_PERF_DOMAIN_PERF_DOMAIN_ID,
	DEVICE_ENERGY_MODEL_A_PERF_DOMAIN_FLAGS,
	DEVICE_ENERGY_MODEL_A_PERF_DOMAIN_CPUS,

	__DEVICE_ENERGY_MODEL_A_PERF_DOMAIN_MAX,
	DEVICE_ENERGY_MODEL_A_PERF_DOMAIN_MAX = (__DEVICE_ENERGY_MODEL_A_PERF_DOMAIN_MAX - 1)
};

enum {
	DEVICE_ENERGY_MODEL_A_PERF_TABLE_PERF_DOMAIN_ID = 1,
	DEVICE_ENERGY_MODEL_A_PERF_TABLE_PERF_STATE,

	__DEVICE_ENERGY_MODEL_A_PERF_TABLE_MAX,
	DEVICE_ENERGY_MODEL_A_PERF_TABLE_MAX = (__DEVICE_ENERGY_MODEL_A_PERF_TABLE_MAX - 1)
};

enum {
	DEVICE_ENERGY_MODEL_A_PERF_STATE_PAD = 1,
	DEVICE_ENERGY_MODEL_A_PERF_STATE_PERFORMANCE,
	DEVICE_ENERGY_MODEL_A_PERF_STATE_FREQUENCY,
	DEVICE_ENERGY_MODEL_A_PERF_STATE_POWER,
	DEVICE_ENERGY_MODEL_A_PERF_STATE_COST,
	DEVICE_ENERGY_MODEL_A_PERF_STATE_FLAGS,

	__DEVICE_ENERGY_MODEL_A_PERF_STATE_MAX,
	DEVICE_ENERGY_MODEL_A_PERF_STATE_MAX = (__DEVICE_ENERGY_MODEL_A_PERF_STATE_MAX - 1)
};

enum {
	DEVICE_ENERGY_MODEL_CMD_GET_PERF_DOMAINS = 1,
	DEVICE_ENERGY_MODEL_CMD_GET_PERF_TABLE,
	DEVICE_ENERGY_MODEL_CMD_PERF_DOMAIN_CREATED,
	DEVICE_ENERGY_MODEL_CMD_PERF_DOMAIN_UPDATED,
	DEVICE_ENERGY_MODEL_CMD_PERF_DOMAIN_DELETED,

	__DEVICE_ENERGY_MODEL_CMD_MAX,
	DEVICE_ENERGY_MODEL_CMD_MAX = (__DEVICE_ENERGY_MODEL_CMD_MAX - 1)
};

#define DEVICE_ENERGY_MODEL_MCGRP_EVENT	"event"

#endif /* _UAPI_LINUX_DEVICE_ENERGY_MODEL_H */
